/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme.ts
 * Command: astryx theme build theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/**
 * echo theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { echoTheme } from './echo';
 *   import './echo.css';
 */
export const echoTheme = {
  name: 'echo',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#FF6B4A, #FF8566)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #231D18)",
    "--color-neutral": "light-dark(#2519161A, #F1DFDA33)",
    "--color-background-surface": "light-dark(#FFFFFF, #231D18)",
    "--color-background-body": "light-dark(#FFF9F5, #171310)",
    "--color-overlay": "light-dark(#25191666, #25191599)",
    "--color-overlay-hover": "light-dark(#2519160D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#2519161A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#2519160D, #25191580)",
    "--color-text-primary": "light-dark(#2A211A, #F5EEE7)",
    "--color-text-secondary": "light-dark(#7A6A5D, #B7A99B)",
    "--color-text-disabled": "light-dark(#A38C86, #6F5A54)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#251916, #F1DFDA)",
    "--color-icon-secondary": "light-dark(#56423D, #BEA6A0)",
    "--color-icon-disabled": "light-dark(#A38C86, #6F5A54)",
    "--color-background-card": "light-dark(#FFFFFF, #231D18)",
    "--color-background-popover": "light-dark(#FFFBF9, #3A2D2A)",
    "--color-background-inverted": "light-dark(#251916, #FFFBF9)",
    "--color-border": "light-dark(#F0E4DA, #3A2F27)",
    "--color-border-emphasized": "light-dark(#A38C86, #79635E)",
    "--color-skeleton": "light-dark(#BEA6A0, #56423D)",
    "--color-track": "light-dark(#BEA6A0, #56423D)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.4286",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.3913",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4737",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4737",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2121",
    "--radius-none": "0px",
    "--radius-inner": "8px",
    "--radius-element": "14px",
    "--radius-container": "20px",
    "--radius-page": "56px",
    "--radius-chat": "56px",
    "--radius-full": "9999px",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "150ms",
    "--duration-medium": "200ms",
    "--duration-medium-max": "265ms",
    "--duration-slow-min": "375ms",
    "--duration-slow": "500ms",
    "--duration-slow-max": "665ms",
    "--font-family-body": "\"PT Sans\", -apple-system, system-ui, sans-serif",
    "--font-family-heading": "Nunito, -apple-system, system-ui, sans-serif",
    "--color-success": "light-dark(#1FA97E, #4FD79A)",
    "--color-warning": "light-dark(#E8A23D, #F0BE6E)",
    "--shadow-low": "0 2px 8px light-dark(rgba(42,33,26,0.06), rgba(0,0,0,0.3))",
    "--shadow-med": "0 12px 24px light-dark(rgba(42,33,26,0.08), rgba(0,0,0,0.35))",
    "--focus-outline-color": "var(--color-accent)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:primary": {
        "fontWeight": "var(--font-weight-bold)",
        ":active": {
          "transform": "translateY(1px) scale(0.99)"
        }
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-container)",
        "boxShadow": "var(--shadow-low), var(--shadow-med)",
        "borderWidth": "0"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.2
      },
      "body": {
        "family": "PT Sans",
        "fallbacks": "-apple-system, system-ui, sans-serif"
      },
      "heading": {
        "family": "Nunito",
        "fallbacks": "-apple-system, system-ui, sans-serif",
        "weight": "bold",
        "weights": {
          "1": "bold",
          "2": "bold",
          "3": "bold"
        }
      }
    },
    "color": {
      "accent": [
        "#FF6B4A",
        "#FF8566"
      ],
      "neutralStyle": "warm",
      "contrast": "standard"
    },
    "radius": {
      "base": 5,
      "multiplier": 1.6
    },
    "motion": {
      "fast": 150,
      "medium": 200,
      "slow": 500,
      "ratio": 0.75
    }
  },

};
